title: Smart Home page | Розумний дім 
author: 👤 Andriuk
email: yurii.andriuk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Розумний дім 
# social links
twitter_username: andriuk # DO NOT include the @ character, or else the build will fail!
github_username:  andriuk # DO NOT include the @ character, or else the build will fail!
instagram_username: yuandrk

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman 